### PR TITLE
Move homepage & appstore UIs to main repo

### PR DESCRIPTION
**Pull request by 0x70b1a5**
Also, fix scrollbar issues.

To test: 
- rebuild kinode and launch a local node
- confirm login page appearance OK
- login
- confirm homepage appearance OK
- confirm app store appearance OK

### CODE REVIEW

**Comment by 0x70b1a5** [comment]
There's definitely some weirdness with the current setup, and you may wish to prevent merge until I write some docs (maybe with @willbach to cover things I don't yet know) about the particulars of modifying it. Or, just add that as a TODO and merge if it looks OK, as the UI is in need of some love anyway.

**Comment by 0x70b1a5** [comment]
@dr-frmr @nick1udwig I think the present state is a good spot to cut a PR - the homepage hasn't been Vite-ified yet but there is enough to test and double-check in the Register flow that I would prefer to close this one out before moving on.

**Comment by 0x70b1a5** [comment]
TODOs as of now:
- Vite up the Homepage
- "    "  "   App Store

**Review by dr-frmr — APPROVED** [review]
"LGTM"

**Pull request merged**
