### PR TITLE
fix build.rs `src/` behavior

### PR DESCRIPTION
**Pull request by nick1udwig**
## Problem

We don't rebuild core processes when their src/ is changed.

## Solution

When we are inside a directory that is contained in `rerun_files`, print all entries therein.

## Docs Update

N/A

## Notes

None

### CODE REVIEW

**Comment by dr-frmr** [comment]
@nick1udwig is there an amortizeable performance cost to all this..? or is it negligible/cost of doing business

**Comment by nick1udwig** [comment]
So the "correct" behavior is that on a rebuild we go and try to `kit build` all the `packages/`. I THINK this PR should do that, but I've thought like 5 iterations of `build.rs` should do that so...

In any case, `kit build` does a good job of rebuilding only when necessary. You can experience this yourself when you `kit b` a package: first time build takes a while; second time with no changes is nearly instant; third time with changes is usually 1-2 seconds on my machine.

**Comment by dr-frmr** [comment]
Oh no I just meant performance of traversing all the directories to find changes and cargo-print them. I suppose that's meaningless compared to build time itself.

**Review by dr-frmr — APPROVED** [review]
LGTM

**Comment by nick1udwig** [comment]
> Oh no I just meant performance of traversing all the directories to find changes and cargo-print them. I suppose that's meaningless compared to build time itself.

Ah, I see. Yeah, I think you are correct: small wrt overall build time.

**Pull request merged**
