### PR TITLE
bump wasmtime deps to 19.0.1

### PR DESCRIPTION
**Pull request by nick1udwig**
## Problem

wasmtime 19.0.1 has some cool stuff

## Solution

Bump the deps

## Docs Update

https://github.com/kinode-dao/kinode-book/issues/153

## Notes

https://github.com/kinode-dao/process_lib/pull/69
https://github.com/kinode-dao/kit/pull/129

### CODE REVIEW

**Comment by nick1udwig** [comment]
Please consider this, the process_lib & kit PRs as a package deal.

@dr-frmr :
For this update, process devs with existing processes will have to:
1. Bump `process_lib` import:
   ```
   process_lib = { git = "https://github.com/kinode-dao/process_lib.git", rev = "84b3d84" }
   ```
2. Bump `wit_bindgen`:
   ```
   wit_bindgen = "0.24.0"
   ```
3. Use the newest `kit`:
   ```
   kit update
   ```
4. Change the `wit_bindgen::generate!()` call to remove the `exports` field:
   ```
   wit_bindgen::generate!({
        path: "wit",
        world: "process",
   });
   ```
5. If not using `call_init!()`, add `export!()` macro call:
   ```
   export!(Component);
   ```

**Comment by nick1udwig** [comment]
I was worried this would break our Py & JS processes because I did not update the libs we use to build those (and even the most recent updates of those libs are not on wasmtime 19.0.1). But I think specifically because of this semver change, they still work! The WASI version between 17.0.1 (what those libs are on) and 19.0.1 must only differ by a patch -> we good. Tested and they work :rocket:

**Comment by dr-frmr** [comment]
Ok, so this is *not* a breaking change? Existing compiled apps run fine?

**Comment by nick1udwig** [comment]
> Ok, so this is _not_ a breaking change? Existing compiled apps run fine?

Confirmed. I can run this binary using [this `kit`](https://github.com/kinode-dao/kit/pull/129) and then, using `kit` on master,

```
kit n foo
kit bs foo
```

and it works :+1: 

```
$ kit f -r ~/git/kinode
...

 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠖⠉
 ⠁⠶⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠔⠋⠀⠀⠀888    d8P  d8b                        888
 ⠀⠀⠈⢛⠿⣷⣦⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡤⠤⣴⡞⠁⠀⠀⠀⠀⠀888   d8P   Y8P                        888
 ⠀⠀⠀⠀⠙⠳⢾⣿⣟⣻⠷⣦⣤⣀⠀⠀⠀⠀⠀⠀⣾⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀888  d8P                               888
 ⠀⠀⠀⠀⠀⠀⠙⠲⣯⣿⣿⣿⣿⠽⢿⣷⣦⣤⣀⠀⢿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀888d88K     888 88888b.   .d88b.   .d88888  .d88b.
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠲⠾⠿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀8888888b    888 888 "88b d88""88b d88" 888 d8P  Y8b
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠛⣛⣯⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀888  Y88b   888 888  888 888  888 888  888 88888888
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠛⡵⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀888   Y88b  888 888  888 Y88..88P Y88b 888 Y8b.
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣱⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀888    Y88b 888 888  888  "Y88P"   "Y88888  "Y8888
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⣿⣿⣿⣿⡽⠋⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⡿⠿⠛⣫⡽⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀fake.os (indirect)
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣯⣷⡞⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀version 0.6.3
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡾⣿⡿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀a general purpose sovereign cloud computer
 ⠀⠀⠀⠀⠀⠀⠀⣠⠴⠛⠉⢰⡿⢱⡿⢹⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⢠⡿⠁⡿⠁⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠟⠀⡸⠁⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 ⠀⠀⠀⠀⠀⠀⠀⢀⠔⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
 networking public key: c71884b82f366b17cef3d18ab135c39ab1a67a5d9ceafe8670a4f4fae908ea35
Fri 09:31 http_server: running on port 8080
Fri 09:31 kns_indexer:sys: indexing on contract address 0x3807fBD692Aa5c96F1D8D7c59a1346a885F40B1C
Fri 09:31 chess:sys: started
Fri 09:31 app_store:sys: started
Fri 09:31 app_store:sys: indexing on contract address 0x18c39eB547A0060C6034f8bEaFB947D1C16eADF1
Fri 09:49 foo:template.os: begin
```

**Review by dr-frmr — APPROVED** [review]
In that case I happily approve.

**Pull request merged**
